version: 2.1
filters:
  branches:
    only: master
jobs:
  build:
    docker:
      - image: maven:3.6.3-jdk-8
    steps:
      - checkout
      - run: mvn clean install
  publish-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ./target
      - run:
          name: "Publish Plugin Release"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./target/TPExp-${PLUGIN_VER}-SNAPSHOT.jar